nzbmounter:
	cd NZBDriveLib && $(MAKE)
	cd NZBFuseDrive && $(MAKE)
	cd NZBMounter && $(MAKE)

clean:
	cd NZBDriveLib && $(MAKE) clean
	cd NZBFuseDrive && $(MAKE) clean
	cd NZBMounter && $(MAKE) clean

